import os, sys, tempfile, time
import h1
spec = h1.spec_base()
b = tempfile.mkdtemp(dir="/tmp/claude-0/t")
t0=time.time()
c = h1.costruisci(b, spec)
print("fixture", time.time()-t0)
srv = h1.Srv(spec)
drv = open(os.path.join(h1.REPO, "backtest_pipeline/righe/RIGA_DUKA_P1_OROLOGIO.ps1"), "rb").read().replace(h1.RAW.encode(), srv.base.encode())
rf = os.path.join(b, "drv.ps1"); open(rf, "wb").write(drv)
args = "-Pin %s -ShaPy %s -ShaF2 %s -ShaImp %s -ShaMq5 %s" % (spec["pin"], srv.sha(h1.FILE_PY), srv.sha(h1.FILE_F2), srv.sha(h1.FILE_IMP), srv.sha(h1.FILE_MQ5))
t0=time.time()
p = h1.esegui(spec, c, rf, args, srv, b)
print("run", time.time()-t0, p.returncode)
print(p.stdout[-6000:]); print("ERR", p.stderr[-3000:])
